/-
Capstone for Chapter 13 (Where to go next), section "Two theorems for
free". Two facts the book explicitly flagged as out of scope for its
from-scratch `Ring`/`Group` (Chapter 8 §5's remark that `fin3Ring` isn't a
`Field`; Chapters 6-7's non-abelian `perm3Group`/`Equiv.Perm (Fin 3)`
example never had subgroups or Lagrange's theorem available), now
delivered via real Mathlib.
-/
import Mathlib

-- §1: ZMod 3 is a field, not just a ring -- the fact Chapter 8 §5
-- explicitly deferred ("a Field would additionally require every
-- nonzero element to be invertible... not part of Ring's axioms and not
-- checked here").
example : Field (ZMod 3) := inferInstance

-- A genuine consequence a mere Ring cannot state: every nonzero element
-- has a multiplicative inverse.
example : ∀ a : ZMod 3, a ≠ 0 → ∃ b, a * b = 1 := by decide

-- §2: Lagrange's theorem, applied to a real subgroup of the S_3 example
-- from Chapters 6-7 (Equiv.Perm (Fin 3)).
example (s : Subgroup (Equiv.Perm (Fin 3))) :
    Nat.card s ∣ Nat.card (Equiv.Perm (Fin 3)) :=
  Subgroup.card_subgroup_dvd_card s

-- Concretely: the cyclic subgroup generated by the 3-cycle has order 3,
-- dividing the order of S_3 itself, which is 6. (`Nat.card`/`orderOf` are
-- defined via classical choice, so they don't reduce under `decide`
-- directly -- route through the relevant lemmas instead, down to a
-- concrete permutation equality/factorial that genuinely does reduce.)
example : Nat.card (Equiv.Perm (Fin 3)) = 6 := by
  rw [Nat.card_eq_fintype_card, Fintype.card_perm, Fintype.card_fin]
  rfl

example : orderOf (finRotate 3) = 3 := by
  apply orderOf_eq_prime
  · decide
  · decide

example : Nat.card (Subgroup.zpowers (finRotate 3)) = 3 := by
  rw [Nat.card_zpowers]
  apply orderOf_eq_prime
  · decide
  · decide
